name: LoginRecords Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test LoginRecords with Ruby 2.5
      uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.5
    - name: Install dependencies
      run: bundle install
    - name: Run rake install
      run: rake install
    - name: Run tests
      run: rake test

    - uses: actions/checkout@v2
    - name: Test LoginRecords with Ruby 3.0
      uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: bundle install
    - name: Run rake install
      run: rake install
    - name: Run tests
      run: rake test
